In [18]:
import pandas as pd
origin_data=pd.read_excel(r'D:/JCE/ML_data.xlsx')
import math
from scipy.integrate import quad
import numpy as np
correlation_data=origin_data.copy()
finial_data=pd.DataFrame()
origin_data
for i in range(int(len(origin_data)/6)):
    for j in range(6):
        k=j+6*i
        if correlation_data.iloc[k,0]<=366.63:
            correlation_data.loc[k,'pethanol*']=10**(5.24677-1598.673/(correlation_data.iloc[k,0]-46.424))
        else: correlation_data.loc[k,'pethanol*']=10**(4.92531-1432.526/(correlation_data.iloc[k,0]-61.819))
        correlation_data.loc[k,'pn_propanol*']=10**(4.87601-1441.629/(correlation_data.iloc[k,0]-74.299))
        correlation_data.loc[k,'γethanol']=1*(1-correlation_data.loc[k,'Vapor phase concentration'])/((correlation_data.loc[k,'pethanol*']*(1-correlation_data.loc[k,'Liquid phase concentration'])))
        correlation_data.loc[k,'γn_propanol']=1*correlation_data.loc[k,'Vapor phase concentration']/((correlation_data.loc[k,'pn_propanol*']*correlation_data.loc[k,'Liquid phase concentration']))
        correlation_data.loc[k,'ln(γn_propanol/γethanol)']=math.log(correlation_data.loc[k,'γn_propanol']/correlation_data.loc[k,'γethanol'])
for g in range(int(len(origin_data)/6)):
    x=correlation_data.loc[g*6:g*6+5,'Liquid phase concentration']
    y=correlation_data.loc[g*6:g*6+5,'ln(γn_propanol/γethanol)']
    f=np.polyfit(x,y,2)
    polynomial = np.poly1d(f)
    result=quad(polynomial, 0, 1)[0]
    def abs_polynomial(x):
        return np.abs(polynomial(x))
    abs_result=quad(abs_polynomial, 0, 1)[0]
    D=abs(result/abs_result)
    if D<=0.05:
        finial_data=pd.concat([finial_data,correlation_data.iloc[g*6:g*6+6]],axis=0)
model_data=finial_data.reset_index(drop=True)
model_data

,Temperature,Liquid phase concentration,Vapor phase concentration,pethanol*,pn_propanol*,γethanol,γn_propanol,ln(γn_propanol/γethanol)
0,351.65,0.0361,0.0300,1.021175,0.476606,0.985461,1.743630,0.570615
1,354.15,0.2470,0.1730,1.126294,0.530388,0.975122,1.320552,0.303242
2,356.05,0.3220,0.1940,1.212080,0.574556,0.980786,1.048608,0.066865
3,358.35,0.5330,0.3220,1.323130,0.632067,1.097262,0.955797,-0.138028
4,362.85,0.6480,0.4280,1.564909,0.758424,1.038399,0.870876,-0.175935
5,364.15,0.6890,0.4610,1.641198,0.798583,1.056008,0.837841,-0.231423
6,351.95,0.0484,0.0330,1.033340,0.482810,0.983397,1.412189,0.361883
7,354.45,0.2180,0.1490,1.139492,0.537168,0.955018,1.272388,0.286921
8,356.15,0.3330,0.2010,1.216741,0.576963,0.984516,1.046174,0.060745
9,358.95,0.5680,0.3530,1.353449,0.647830,1.106569,0.959325,-0.142790
10,362.95,0.7270,0.5120,1.570672,0.761453,1.138077,0.924895,-0.207415
11,365.85,0.7550,0.5590,1.745579,0.853731,1.031177,0.867249,-0.173130
12,352.05,0.0640,0.0392,1.037421,0.484892,0.989468,1.263167,0.244210
13,354.55,0.2540,0.1590,1.143920,0.539444,0.985511,1.160425,0.163382
14,356.25,0.4040,0.2400,1.221417,0.579378,1.044007,1.025340,-0.018042
15,359.25,0.5200,0.3140,1.368824,0.655832,1.044084,0.920733,-0.125725
16,363.05,0.7080,0.4950,1.576451,0.764492,1.097054,0.914533,-0.181971
17,366.15,0.9270,0.8520,1.764556,0.863781,1.148956,1.064035,-0.076785
18,352.15,0.1520,0.1060,1.041517,0.486982,1.012221,1.432020,0.346939
19,354.65,0.2620,0.1620,1.148363,0.541728,0.988800,1.141386,0.143506
20,356.55,0.3100,0.1660,1.235536,0.586674,0.978276,0.912746,-0.069334
21,359.35,0.4570,0.2620,1.373981,0.658518,0.989181,0.870598,-0.127698
22,363.15,0.6390,0.4080,1.582248,0.767540,1.036430,0.831875,-0.219855
23,366.35,0.8520,0.7080,1.777302,0.870536,1.110094,0.954569,-0.150941
24,353.05,0.1320,0.0799,1.078983,0.506134,0.982428,1.195935,0.196656
25,354.75,0.2440,0.1560,1.152819,0.544020,0.968410,1.175222,0.193557
26,356.75,0.3640,0.2080,1.245024,0.591580,1.000208,0.965937,-0.034865
27,359.95,0.4740,0.2840,1.405263,0.674824,0.968657,0.887870,-0.087085
28,363.25,0.6300,0.4120,1.588063,0.770599,1.000709,0.848649,-0.164818
29,366.55,0.8620,0.7360,1.790124,0.877333,1.068665,0.973209,-0.093567
30,353.15,0.1060,0.0735,1.083214,0.508300,0.956739,1.364148,0.354754
31,354.85,0.2470,0.1390,1.157291,0.546320,0.988020,1.030080,0.041689
32,356.85,0.3220,0.1870,1.249791,0.594045,0.959453,0.977611,0.018749
33,360.05,0.4280,0.2730,1.410533,0.677574,0.901063,0.941374,0.043765
34,363.45,0.5810,0.3680,1.599746,0.776747,0.942870,0.815441,-0.145200
35,366.75,0.9020,0.8080,1.688265,0.884175,1.160472,1.013134,-0.135778
36,353.25,0.0959,0.0609,1.087459,0.510474,0.955174,1.244014,0.264205
37,354.95,0.2770,0.1830,1.161776,0.548628,0.972661,1.204186,0.213524
38,356.95,0.4120,0.2470,1.254573,0.596520,1.020756,1.005021,-0.015535
39,361.15,0.6250,0.3960,1.469600,0.708440,1.095990,0.894359,-0.203306
40,363.55,0.6570,0.4320,1.605614,0.779836,1.031366,0.843170,-0.201471
41,366.85,0.9320,0.8670,1.694263,0.887612,1.154415,1.048045,-0.096667
42,353.35,0.1220,0.0831,1.091718,0.512655,0.956570,1.328666,0.328577
43,355.05,0.2250,0.1460,1.166276,0.550944,0.944832,1.177776,0.220376
44,357.25,0.3180,0.1800,1.269009,0.603994,0.947468,0.937158,-0.010941
45,361.55,0.6850,0.4780,1.491581,0.719949,1.110997,0.969250,-0.136491
46,363.65,0.6160,0.3800,1.611500,0.782935,1.001913,0.787911,-0.240281
47,366.95,0.9580,0.9170,1.700278,0.891060,1.162275,1.074229,-0.078776
48,353.45,0.1590,0.0992,1.095991,0.514844,0.977294,1.211821,0.215092
49,355.15,0.2730,0.1800,1.170791,0.553268,0.963386,1.191719,0.212698
50,357.35,0.3290,0.1940,1.273852,0.606502,0.942961,0.972240,0.030578
51,361.75,0.6520,0.4000,1.502673,0.725761,1.147380,0.845316,-0.305527
52,363.75,0.7170,0.5070,1.617404,0.786044,1.077065,0.899585,-0.180062
53,367.15,0.9680,0.9380,1.712360,0.897989,1.131479,1.079087,-0.047411
54,351.15,0.0269,0.0209,1.001166,0.466415,1.004994,1.665796,0.505322
55,353.95,0.1830,0.1220,1.117565,0.525908,0.961611,1.267650,0.276310
56,355.95,0.3760,0.2040,1.207433,0.572158,1.056490,0.948258,-0.108081
57,357.45,0.3490,0.1760,1.278710,0.609019,0.989861,0.828049,-0.178492
58,362.55,0.7360,0.5330,1.547728,0.749398,1.142926,0.966355,-0.167816
59,363.95,0.6340,0.4160,1.629265,0.792293,0.979355,0.828168,-0.167678

In [19]:
f_data=pd.DataFrame()
x=model_data.loc[:,'Liquid phase concentration']
y=model_data.loc[:,'ln(γn_propanol/γethanol)']
f1=np.polyfit(x,y,2)
polynomial1 = np.poly1d(f)
result1=quad(polynomial1, 0, 1)[0]
def abs_polynomial1(x):
    return np.abs(polynomial1(x))
abs_result1=quad(abs_polynomial1, 0, 1)[0]
D=abs(result1/abs_result1)
if D<=0.05:
    f_data=model_data
f_data.to_excel(r'D:/JCE/model_data.xlsx')
f_data

,Temperature,Liquid phase concentration,Vapor phase concentration,pethanol*,pn_propanol*,γethanol,γn_propanol,ln(γn_propanol/γethanol)
0,351.65,0.0361,0.0300,1.021175,0.476606,0.985461,1.743630,0.570615
1,354.15,0.2470,0.1730,1.126294,0.530388,0.975122,1.320552,0.303242
2,356.05,0.3220,0.1940,1.212080,0.574556,0.980786,1.048608,0.066865
3,358.35,0.5330,0.3220,1.323130,0.632067,1.097262,0.955797,-0.138028
4,362.85,0.6480,0.4280,1.564909,0.758424,1.038399,0.870876,-0.175935
5,364.15,0.6890,0.4610,1.641198,0.798583,1.056008,0.837841,-0.231423
6,351.95,0.0484,0.0330,1.033340,0.482810,0.983397,1.412189,0.361883
7,354.45,0.2180,0.1490,1.139492,0.537168,0.955018,1.272388,0.286921
8,356.15,0.3330,0.2010,1.216741,0.576963,0.984516,1.046174,0.060745
9,358.95,0.5680,0.3530,1.353449,0.647830,1.106569,0.959325,-0.142790
10,362.95,0.7270,0.5120,1.570672,0.761453,1.138077,0.924895,-0.207415
11,365.85,0.7550,0.5590,1.745579,0.853731,1.031177,0.867249,-0.173130
12,352.05,0.0640,0.0392,1.037421,0.484892,0.989468,1.263167,0.244210
13,354.55,0.2540,0.1590,1.143920,0.539444,0.985511,1.160425,0.163382
14,356.25,0.4040,0.2400,1.221417,0.579378,1.044007,1.025340,-0.018042
15,359.25,0.5200,0.3140,1.368824,0.655832,1.044084,0.920733,-0.125725
16,363.05,0.7080,0.4950,1.576451,0.764492,1.097054,0.914533,-0.181971
17,366.15,0.9270,0.8520,1.764556,0.863781,1.148956,1.064035,-0.076785
18,352.15,0.1520,0.1060,1.041517,0.486982,1.012221,1.432020,0.346939
19,354.65,0.2620,0.1620,1.148363,0.541728,0.988800,1.141386,0.143506
20,356.55,0.3100,0.1660,1.235536,0.586674,0.978276,0.912746,-0.069334
21,359.35,0.4570,0.2620,1.373981,0.658518,0.989181,0.870598,-0.127698
22,363.15,0.6390,0.4080,1.582248,0.767540,1.036430,0.831875,-0.219855
23,366.35,0.8520,0.7080,1.777302,0.870536,1.110094,0.954569,-0.150941
24,353.05,0.1320,0.0799,1.078983,0.506134,0.982428,1.195935,0.196656
25,354.75,0.2440,0.1560,1.152819,0.544020,0.968410,1.175222,0.193557
26,356.75,0.3640,0.2080,1.245024,0.591580,1.000208,0.965937,-0.034865
27,359.95,0.4740,0.2840,1.405263,0.674824,0.968657,0.887870,-0.087085
28,363.25,0.6300,0.4120,1.588063,0.770599,1.000709,0.848649,-0.164818
29,366.55,0.8620,0.7360,1.790124,0.877333,1.068665,0.973209,-0.093567
30,353.15,0.1060,0.0735,1.083214,0.508300,0.956739,1.364148,0.354754
31,354.85,0.2470,0.1390,1.157291,0.546320,0.988020,1.030080,0.041689
32,356.85,0.3220,0.1870,1.249791,0.594045,0.959453,0.977611,0.018749
33,360.05,0.4280,0.2730,1.410533,0.677574,0.901063,0.941374,0.043765
34,363.45,0.5810,0.3680,1.599746,0.776747,0.942870,0.815441,-0.145200
35,366.75,0.9020,0.8080,1.688265,0.884175,1.160472,1.013134,-0.135778
36,353.25,0.0959,0.0609,1.087459,0.510474,0.955174,1.244014,0.264205
37,354.95,0.2770,0.1830,1.161776,0.548628,0.972661,1.204186,0.213524
38,356.95,0.4120,0.2470,1.254573,0.596520,1.020756,1.005021,-0.015535
39,361.15,0.6250,0.3960,1.469600,0.708440,1.095990,0.894359,-0.203306
40,363.55,0.6570,0.4320,1.605614,0.779836,1.031366,0.843170,-0.201471
41,366.85,0.9320,0.8670,1.694263,0.887612,1.154415,1.048045,-0.096667
42,353.35,0.1220,0.0831,1.091718,0.512655,0.956570,1.328666,0.328577
43,355.05,0.2250,0.1460,1.166276,0.550944,0.944832,1.177776,0.220376
44,357.25,0.3180,0.1800,1.269009,0.603994,0.947468,0.937158,-0.010941
45,361.55,0.6850,0.4780,1.491581,0.719949,1.110997,0.969250,-0.136491
46,363.65,0.6160,0.3800,1.611500,0.782935,1.001913,0.787911,-0.240281
47,366.95,0.9580,0.9170,1.700278,0.891060,1.162275,1.074229,-0.078776
48,353.45,0.1590,0.0992,1.095991,0.514844,0.977294,1.211821,0.215092
49,355.15,0.2730,0.1800,1.170791,0.553268,0.963386,1.191719,0.212698
50,357.35,0.3290,0.1940,1.273852,0.606502,0.942961,0.972240,0.030578
51,361.75,0.6520,0.4000,1.502673,0.725761,1.147380,0.845316,-0.305527
52,363.75,0.7170,0.5070,1.617404,0.786044,1.077065,0.899585,-0.180062
53,367.15,0.9680,0.9380,1.712360,0.897989,1.131479,1.079087,-0.047411
54,351.15,0.0269,0.0209,1.001166,0.466415,1.004994,1.665796,0.505322
55,353.95,0.1830,0.1220,1.117565,0.525908,0.961611,1.267650,0.276310
56,355.95,0.3760,0.2040,1.207433,0.572158,1.056490,0.948258,-0.108081
57,357.45,0.3490,0.1760,1.278710,0.609019,0.989861,0.828049,-0.178492
58,362.55,0.7360,0.5330,1.547728,0.749398,1.142926,0.966355,-0.167816
59,363.95,0.6340,0.4160,1.629265,0.792293,0.979355,0.828168,-0.167678